<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ header }} - MODULE Examples</title>

</head>

<body>

    <h1>Main Application Layout</h1>

    {% block section %}{% endblock %}

</body>
</html>
